# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c07b533e329b86dd3f688bcc3ba88caabb18c3358af8da974b925dec5d3000dcd30d24e74054983f93c5815274abbdc676b7e3d82514a8ea33a5e72c75a34d1d

test:
  secret_key_base: 67a81bb4739573c25a6f73c7b247b892478aa7587f86145ec9856344a4a329f2fad871f90afe9a74cd97d4940df4b5fbf2a50d82a4641179182132b3f4d464fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
